name: Cookie Monitoring and Renewal

permissions:
  contents: write

on:
  schedule:
    - cron: '0 */12 * * *'

  # Manual trigger
  workflow_dispatch:
    inputs:
      force_refresh:
        description: 'Force refresh manually'
        default: 'false'
        required: false
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  check-and-refresh-cookies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Download previous cookies if they exist
        continue-on-error: true
        run: |
          if [ -f ".cookies-archive/captured-cookies.json" ]; then
            cp .cookies-archive/captured-cookies.json ./captured-cookies.json
          fi

      - name: Decide if cookie refresh is needed
        run: |
          if [ "${{ github.event.inputs.force_refresh }}" == "true" ]; then
            echo "REFRESH_NEEDED=true" >> $GITHUB_ENV
            echo "Manual refresh requested"
          else
            echo "REFRESH_NEEDED=true" >> $GITHUB_ENV
            echo "Auto refresh triggered on schedule"
          fi

      - name: Refresh cookies
        if: env.REFRESH_NEEDED == 'true'
        run: node app.js

      - name: Create archive directory
        run: mkdir -p .cookies-archive

      - name: Store cookies
        run: cp captured-cookies.json .cookies-archive/captured-cookies.json

      - name: Commit and push updated cookies
        if: env.REFRESH_NEEDED == 'true'
        run: |
          git config --global user.name 'Cookie Refresh Bot'
          git config --global user.email 'bot@github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git add captured-cookies.json .cookies-archive/captured-cookies.json
          git diff --staged --quiet || (git commit -m "Update cookies - $(date -u +'%Y-%m-%d %H:%M:%S UTC')" && git push origin HEAD)

